### PR TITLE
Styling game screen

### PR DESCRIPTION
**Pull request by Flaagrah**
Styled game screen to look like the spec.

### CODE REVIEW

**Comment by haruka-izm** [comment]
It looks good. It would be great to have a scrollbar. For instance, in my computer, the game page needs to be zoomed out to see all cards.

e1

**Comment by Flaagrah** [comment]
Added scrolling

**Comment by pavel6767** [comment]
- Looks good, on a narrower screen, the words in the cards get eaten though

image

- I'm guessing the NaN guesses left bug gets solved with the merge

**Review by pavel6767 — APPROVED** [review]

**Review by haruka-izm — APPROVED** [review]

**Comment by aeciorc** [comment]
I'm 3 minutes late, but I'd like to see the card blue and red colors being the same as the ones used in the navbar

**Pull request merged**
